#define _NAME(name) #name

#define ICON_MAIN 100

#define STR_APP_NAME 200
#define STR_DO_NOTHING 201
#define STR_SLEEP 202
#define STR_HIBERNATE 203
#define STR_SHUT_DOWN 204
#define STR_USING_BATTERY 205
#define STR_PLUGGED_IN 206
#define STR_FMT_ON_BATTERY 207
#define STR_FMT_PLUGGED_IN 208
#define STR_FMT_MONITOR_CONNECTED_DC 209
#define STR_FMT_MONITOR_CONNECTED_AC 210
#define STR_FMT_MONITOR_DISCONNECTED_DC 211
#define STR_FMT_MONITOR_DISCONNECTED_AC 212
#define STR_SYNC_MONITOR 213
#define STR_WHEN_LID_CLOSING 214
#define STR_EXIT 215
#define STR_START_ON_BOOT 216
#define STR_ON 217
#define STR_OFF 218
#define STR_UNKNOWN 219
#define STR_ALREADY_RUNNING 220
